//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.NationalCriminalsWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonSearchParametersDto", Namespace="http://schemas.datacontract.org/2004/07/WCF.Contracts")]
    [System.SerializableAttribute()]
    public partial class PersonSearchParametersDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AgeFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AgeToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> HeightFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> HeightToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> WeightFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> WeightToField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AgeFrom {
            get {
                return this.AgeFromField;
            }
            set {
                if ((this.AgeFromField.Equals(value) != true)) {
                    this.AgeFromField = value;
                    this.RaisePropertyChanged("AgeFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AgeTo {
            get {
                return this.AgeToField;
            }
            set {
                if ((this.AgeToField.Equals(value) != true)) {
                    this.AgeToField = value;
                    this.RaisePropertyChanged("AgeTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> HeightFrom {
            get {
                return this.HeightFromField;
            }
            set {
                if ((this.HeightFromField.Equals(value) != true)) {
                    this.HeightFromField = value;
                    this.RaisePropertyChanged("HeightFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> HeightTo {
            get {
                return this.HeightToField;
            }
            set {
                if ((this.HeightToField.Equals(value) != true)) {
                    this.HeightToField = value;
                    this.RaisePropertyChanged("HeightTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sex {
            get {
                return this.SexField;
            }
            set {
                if ((object.ReferenceEquals(this.SexField, value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> WeightFrom {
            get {
                return this.WeightFromField;
            }
            set {
                if ((this.WeightFromField.Equals(value) != true)) {
                    this.WeightFromField = value;
                    this.RaisePropertyChanged("WeightFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> WeightTo {
            get {
                return this.WeightToField;
            }
            set {
                if ((this.WeightToField.Equals(value) != true)) {
                    this.WeightToField = value;
                    this.RaisePropertyChanged("WeightTo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NationalCriminalsWebService.IPersonWebService")]
    public interface IPersonWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonWebService/Search", ReplyAction="http://tempuri.org/IPersonWebService/SearchResponse")]
        bool Search(Web.NationalCriminalsWebService.PersonSearchParametersDto personSearchParameters, int maxNumberOfResults, string emailForResults);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonWebService/Search", ReplyAction="http://tempuri.org/IPersonWebService/SearchResponse")]
        System.Threading.Tasks.Task<bool> SearchAsync(Web.NationalCriminalsWebService.PersonSearchParametersDto personSearchParameters, int maxNumberOfResults, string emailForResults);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPersonWebServiceChannel : Web.NationalCriminalsWebService.IPersonWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PersonWebServiceClient : System.ServiceModel.ClientBase<Web.NationalCriminalsWebService.IPersonWebService>, Web.NationalCriminalsWebService.IPersonWebService {
        
        public PersonWebServiceClient() {
        }
        
        public PersonWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PersonWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Search(Web.NationalCriminalsWebService.PersonSearchParametersDto personSearchParameters, int maxNumberOfResults, string emailForResults) {
            return base.Channel.Search(personSearchParameters, maxNumberOfResults, emailForResults);
        }
        
        public System.Threading.Tasks.Task<bool> SearchAsync(Web.NationalCriminalsWebService.PersonSearchParametersDto personSearchParameters, int maxNumberOfResults, string emailForResults) {
            return base.Channel.SearchAsync(personSearchParameters, maxNumberOfResults, emailForResults);
        }
    }
}
